### ISSUE TITLE
Не воспроизводит музыку

### ISSUE THREAD

**Issue by pooh2pooh** [NorthernBlow/PlayMe#1]
**Устанавливаю**, а __он__ музыку ~~не воспроизводит~~. Я **не слышу** ничего.

**Comment by NorthernBlow** [comment]
нам очень жаль.

**Comment by pooh2pooh** [comment]
> нам очень жаль. компьютер перезагружали?

Да. Сначала я перезагрузил свой компьютер. Потом пошёл к соседу и перезагрузил его компьютер. Затем поехал на работу и перезагрузил там все компьютеры, на всякий случай перезагрузил холодильник и микроволновку.
В общем решил пока без музыки. Когда куплю колонки, попробую ещё раз всё перезагрузить.

**Comment by NorthernBlow** [comment]
хорошая идея, держите в курсе. если ничего не получится, мы попробуем что-нибудь исправить.
